create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  company text,
  budget text,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.leads enable row level security;

revoke all on table public.leads from anon, authenticated;
grant insert (name, email, message, company, budget) on table public.leads to anon;
grant usage, select on sequence public.leads_id_seq to anon;

drop policy if exists "Allow anonymous lead inserts" on public.leads;
create policy "Allow anonymous lead inserts"
  on public.leads
  for insert
  to anon
  with check (true);
